### ISSUE TITLE
Search result display CSS issue 

### ISSUE THREAD

**Issue by CameronNicolson** [CameronNicolson/Leaf-It-To-Us#18]
CSS property `.teabox` 

![2018-03-20 1](https://user-images.githubusercontent.com/6314429/37661848-9a0459f4-2c4d-11e8-86f3-3783f1b9b447.png)

**Comment by vitawood** [comment]
Done but not pushed

**Comment by CameronNicolson** [comment]
Fix pushed 8536bba8495236e7a29857f52b9ae26c9d2b8045 in recent commit
