### ISSUE TITLE
Contact us form not working

### ISSUE THREAD

**Issue by vitawood** [CameronNicolson/Leaf-It-To-Us#22]
Set it to email me on submit, all it does is open up a blank page on Chrome??

**Comment by CameronNicolson** [comment]
Windows 10 > default apps > set email to outlook etc

It worked for me. It is not a very stable way because you need to allow email as your default app for opening mailto links, and not everyone uses these settings.

**Comment by vitawood** [comment]
Can we agree it's not worth changing at this point though

**Comment by CameronNicolson** [comment]
Agreed
