### ISSUE TITLE
IndexError on homepage when database is not populated

### ISSUE THREAD

**Issue by CameronNicolson** [CameronNicolson/Leaf-It-To-Us#27]
![screen shot 2018-03-21 at 16 43 15](https://user-images.githubusercontent.com/6314429/37724298-52fe1d34-2d28-11e8-9dab-d5c9f8137dea.png)

**Comment by vitawood** [comment]
Surely this is expected though?

**Comment by CameronNicolson** [comment]
Bug has been fixed c9f0c3fd032a269681230727157fc7f67b7ed7e2
